### ISSUE TITLE
+ setup up files --

### ISSUE THREAD

**Issue by dualfade** [nicholasaleks/CrackQL#8]
Hey guys, 
I would like to add this to the Blackarch Linux release. Would it be possible to add a setup.py or pyproject.toml ? I've already generated the package but it does complain on installation about the missing file.

It's great tool. I used it on my last engagement. Well done. 

Let me know.
Thank you !
Sincerely,

**Comment by nicholasaleks** [comment]
Hey @dualfade 

Really glad to hear you're enjoying CrackQL! I'll set aside sometime to add a setup script.

P.S: If you're into GraphQL hacking check this out (https://nostarch.com/black-hat-graphql)

**Comment by dualfade** [comment]
ah awesome !! Congrats on that as well. I will definitely get a copy ( once available ). Yeah please let me know and I'll re push the package. 

Thank you !!
Sincerely

**Comment by noraj** [comment]
But as both `setup.py` and `requirements.txt` are deprecated now, I suggest following [PEP 517](https://peps.python.org/pep-0517/), [PEP 518](https://peps.python.org/pep-0518/), [621](https://peps.python.org/pep-0621/), [660](https://peps.python.org/pep-0660/) and move to the modern `pyproject.toml`.

Using `pyproject.toml` would allow the user or distro packager to either use [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html), [pip](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/), [poetry](https://python-poetry.org/docs/pyproject/), [flit](https://flit.pypa.io/en/latest/pyproject_toml.html), etc.

Update : 👍🏻 for #9

**Comment by dualfade** [comment]
Thank you all very much. Once that is reviewed and merged I will re push my commits to blackarch.

Appreciate it !

**Comment by dualfade** [comment]
Afternoon, 
Let me know when you push the pyproject.toml to master and I will re push this package. 

Appreciate it !
Sincerely,

**Comment by nicholasaleks** [comment]
@dualfade ✅ merged

**Comment by dualfade** [comment]
Fantastic ! Just re pushed. 

Thank you !
